### ISSUE TITLE
Headphones monitoring of stereo sound.

### ISSUE THREAD

**Issue by nowgad** [suzumushi0/SoundObject_binary#5]
Hello!  Somewhere in your explanations you said that if there is demand, then you will be able to provide, create, a SoundObject option for mixing on headphones.  I think that, like me, many people are hesitant to ask you, is it possible to do this?  Is it possible to create a plugin version that is immediately suitable for these purposes?  I think that many are waiting for this, but do not dare to ask.  Thank you!  Thank you for the wonderful, useful programs you create!

**Comment by suzumushi0** [comment]
Yes. If there is sufficient demand, I will release a special version of SuoundObject for headphones monitoring of stereo sound. Does anyone else interest in it?

**Comment by Mrugalla** [comment]
Binaural panning for headphones typically sounds much nicer when you actually are on headphones, but causes more phasing in mono when listening on speakers. I do like that option, too, though. I mean, when I'm using binaural panners at all, I like to go all in with it. Cause otherwise it is too tempting to just use a normal panner instead of simplicity of workflow

**Comment by suzumushi0** [comment]
It seems to me that there are sufficient demands :-). All right, but I am slightly busy toward the end of the year, so please wait a moment.

**Comment by suzumushi0** [comment]
Done.
https://github.com/suzumushi0/SpeakerObjects_binary
